In [6]:
import pandas as pd
import numpy as np
print(f' Pandas: {pd.__version__}')
print(f' Numpy: {np.__version__}')

 Pandas: 2.0.3
 Numpy: 1.24.4

In [14]:
# CELDA 2: CARGA DATASET ORIGINAL
df = pd.read_csv('data/failed_logins.csv')  
print(f' Columnas: {list(df.columns)}')
print('\n Primeras 5 filas:')
display(df.head(20))

 Columnas: ['event_id', 'username', 'role', 'status', 'timestamp', 'ip_address', 'location', 'device', 'account_status', 'login_attempts', 'source_port', 'last_success_login', 'alert_flag']

 Primeras 5 filas:

,event_id,username,role,status,timestamp,ip_address,location,device,account_status,login_attempts,source_port,last_success_login,alert_flag
0,1.0,ROOT,USER,failed,06/08/2024 16:50,165.93.148.165,DE,NaN,inactive,NaN,443.0,2024-06-11 16:50:00,-1
1,NaN,jdoe,guest,failed,19/06/2024 22:06,221.49.14.175,spain,ubuntu,locked,5+,443.0,2024-06-06 22:06:00,yes
2,3.0,service,USER,failed,2024-08-04 22:14:00,242.73.33.181,España,Windows,active,three,3389.0,06-12-2024 22:14,no
3,4.0,admin,guest,failed,06-18-2024 07:47,251.233.216.87,spain,Win,active,4,65536.0,2024-05-20 07:47:00,no
4,5.0,backup,admin,FAIL,04-22-2024 10:04,205.59.238.115,ES,Win,active,5+,8080.0,2024-02-29 10:04:00,0
5,6.0,service,USER,fallido,05-09-2024 21:44,231.118.88.233,USA,NaN,locked,6,22.0,NaN,yes
6,7.0,guest,admin,success,02/09/2024 02:30,97.230.234.167,ES,Win,locked,2,443.0,07-08-2024 02:30,-1
7,8.0,backup,guest,success,02-19-2024 15:28,52.89.166.75,USA,Android,inactive,three,3389.0,29/12/2023 15:28,yes
8,9.0,jdoe,admin,locked,04-27-2024 01:30,250.126.61.226,ES,Linux,active,5+,8080.0,2024-03-28 01:30:00,1
9,10.0,operator,guest,fallido,12/04/2024 12:37,139.172.72.21,España,Android,inactive,4,3389.0,2024-03-31 12:37:00,-1
10,11.0,sysadmin,USER,fallido,13/01/2024 22:48,66.105.134.168,us,Win,locked,three,22.0,06/01/2024 22:48,no
11,12.0,OPERATOR,user,failed,2024-04-27 02:18:00,253.145.13.1,Germany,Linux,active,NaN,NaN,07/04/2024 02:18,no
12,13.0,jdoe,user,success,2024-03-27 23:59:00,198.240.120.65,Unknown,ubuntu,locked,4,22.0,NaN,-1
13,14.0,jdoe,USER,locked,11/07/2024 08:03,119.200.221.185,FR,MacOS,locked,5+,3389.0,2024-07-04 08:03:00,no
14,15.0,sysadmin,admin,failed,05-30-2024 04:41,3.74.50.214,spain,MacOS,inactive,1,3389.0,05-23-2024 04:41,1
15,16.0,it_manager,guest,FAIL,24/02/2024 17:28,74.208.228.137,USA,Linux,inactive,three,80.0,2024-01-29 17:28:00,1
16,17.0,backup,admin,FAIL,03-04-2024 06:40,189.229.239.1,ES,MacOS,inactive,three,8080.0,2024-01-22 06:40:00,-1
17,18.0,operator,USER,locked,04-12-2024 22:34,12.179.49.129,France,Win,inactive,5+,22.0,2024-04-02 22:34:00,yes
18,19.0,root,ADMIN,fallido,2024-05-19 04:19:00,165.62.183.83,DE,NaN,inactive,1,NaN,31/03/2024 04:19,no
19,20.0,sysadmin,user,success,2024-09-08 19:50:00,105.83.180.187,DE,ubuntu,inactive,NaN,22.0,09-06-2024 19:50,yes

In [15]:
# Identifica nulos, duplicados y tipos datos
print('Nulos por columna:')
print(df.isnull().sum())
print(f'\nDuplicados totales: {df.duplicated().sum()}')
print('\nTipos de datos:')
print(df.dtypes)

Nulos por columna:
event_id               110
username                 0
role                     0
status                   0
timestamp                0
ip_address               0
location                 0
device                1231
account_status           0
login_attempts        2499
source_port           1381
last_success_login    1003
alert_flag               0
dtype: int64

Duplicados totales: 0

Tipos de datos:
event_id              float64
username               object
role                   object
status                 object
timestamp              object
ip_address             object
location               object
device                 object
account_status         object
login_attempts         object
source_port           float64
last_success_login     object
alert_flag             object
dtype: object

In [16]:
# Elimina NaN y crea IDs únicos perfectos
df['event_id'] = range(1, len(df) + 1)
df['event_id'] = df['event_id'].astype(int)
print(f' event_id: 1  {df["event_id"].max()} (0 NaN)')
print(df[['event_id', 'username']].head())

 event_id: 1  10000 (0 NaN)
   event_id username
0         1     ROOT
1         2     jdoe
2         3  service
3         4    admin
4         5   backup

In [17]:
df.head()

,event_id,username,role,status,timestamp,ip_address,location,device,account_status,login_attempts,source_port,last_success_login,alert_flag
0,1,ROOT,USER,failed,06/08/2024 16:50,165.93.148.165,DE,NaN,inactive,NaN,443.0,2024-06-11 16:50:00,-1
1,2,jdoe,guest,failed,19/06/2024 22:06,221.49.14.175,spain,ubuntu,locked,5+,443.0,2024-06-06 22:06:00,yes
2,3,service,USER,failed,2024-08-04 22:14:00,242.73.33.181,España,Windows,active,three,3389.0,06-12-2024 22:14,no
3,4,admin,guest,failed,06-18-2024 07:47,251.233.216.87,spain,Win,active,4,65536.0,2024-05-20 07:47:00,no
4,5,backup,admin,FAIL,04-22-2024 10:04,205.59.238.115,ES,Win,active,5+,8080.0,2024-02-29 10:04:00,0

In [18]:
# Quita espacios, minúsculas consistentes
text_cols = ['username', 'role', 'status', 'location', 'device', 'account_status']
for col in text_cols:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.lower()

print(' Texto normalizado (lowercase + strip)')
print(df[text_cols].head())

 Texto normalizado (lowercase + strip)
  username   role  status location   device account_status
0     root   user  failed       de      nan       inactive
1     jdoe  guest  failed    spain   ubuntu         locked
2  service   user  failed   españa  windows         active
3    admin  guest  failed    spain      win         active
4   backup  admin    fail       es      win         active

In [19]:
df.head()

,event_id,username,role,status,timestamp,ip_address,location,device,account_status,login_attempts,source_port,last_success_login,alert_flag
0,1,root,user,failed,06/08/2024 16:50,165.93.148.165,de,nan,inactive,NaN,443.0,2024-06-11 16:50:00,-1
1,2,jdoe,guest,failed,19/06/2024 22:06,221.49.14.175,spain,ubuntu,locked,5+,443.0,2024-06-06 22:06:00,yes
2,3,service,user,failed,2024-08-04 22:14:00,242.73.33.181,españa,windows,active,three,3389.0,06-12-2024 22:14,no
3,4,admin,guest,failed,06-18-2024 07:47,251.233.216.87,spain,win,active,4,65536.0,2024-05-20 07:47:00,no
4,5,backup,admin,fail,04-22-2024 10:04,205.59.238.115,es,win,active,5+,8080.0,2024-02-29 10:04:00,0

In [20]:
# CELDA 6: ESTANDARIZAR ROLES (3 únicos)
# USER/admin/guest → admin/user/guest
role_map = {
    'user': 'user', 'admin': 'admin', 'guest': 'guest',
    'administrator': 'admin', 'sysadmin': 'admin', 
    'root': 'admin', 'service': 'user', 'backup': 'admin'
}
df['role'] = df['role'].replace(role_map)
print(' Roles únicos (3):')
print(df['role'].value_counts())

 Roles únicos (3):
role
admin    5013
user     3314
guest    1673
Name: count, dtype: int64

In [21]:
# CELDA 7: ESTANDARIZAR STATUS (3 únicos)
# failed/FAIL/fallido → failed/success/locked
status_map = {
    'failed': 'failed', 'fail': 'failed', 'fallido': 'failed',
    'success': 'success', 'locked': 'locked'
}
df['status'] = df['status'].replace(status_map)
print(' Status únicos (3):')
print(df['status'].value_counts())

 Status únicos (3):
status
failed     6001
success    2030
locked     1969
Name: count, dtype: int64

In [22]:
# CELDA 8: DEVICE → 0 NULOS
# win→Windows, ubuntu→Ubuntu, NaN→Unknown
print(f'Device NaN antes: {df["device"].isnull().sum()}')
df['device'] = df['device'].replace({'win': 'windows', 'wint': 'windows'})
df['device'] = df['device'].str.capitalize().fillna('Unknown')
print(f' Device NaN después: {df["device"].isnull().sum()}')
print(df['device'].value_counts().head())

Device NaN antes: 0
 Device NaN después: 0
device
Windows    2529
Linux      1317
Android    1263
Nan        1231
Macos      1230
Name: count, dtype: int64

In [23]:
#LOGIN_ATTEMPTS → Unknown/Números
# "three"→3, NaN→Unknown
print(f'Login_attempts NaN antes: {df["login_attempts"].isnull().sum()}')
df['login_attempts'] = df['login_attempts'].astype(str)
df['login_attempts'] = df['login_attempts'].replace({'nan': 'Unknown', 'na': 'Unknown', 'three': '3'})
df['login_attempts'] = pd.to_numeric(df['login_attempts'], errors='coerce').fillna('Unknown')
print(' Login_attempts limpios:')
print(df['login_attempts'].value_counts(dropna=False).head())

Login_attempts NaN antes: 2499
 Login_attempts limpios:
login_attempts
Unknown    5026
3.0        2737
2.0         285
7.0         263
10.0        254
Name: count, dtype: int64

In [24]:
# CELDA 10: SOURCE_PORT → Puertos válidos
# 0-65535 válidos, resto→unknown
def clean_port(port):
    try:
        val = int(float(str(port)))
        return val if 0 <= val <= 65535 else 'unknown'
    except:
        return 'unknown'

print(f'Source_port NaN antes: {df["source_port"].isnull().sum()}')
df['source_port'] = df['source_port'].apply(clean_port).fillna('unknown')
print(' Source_port válidos:')
print(df['source_port'].value_counts().head())

Source_port NaN antes: 1381
 Source_port válidos:
source_port
unknown    2852
443        1458
3389       1454
80         1454
22         1435
Name: count, dtype: int64

In [25]:
# CELDA 11: ALERT_FLAG → 0/1
# yes/no/-1/0/1 → binario 0/1
df['alert_flag'] = df['alert_flag'].astype(str).str.lower()
df['alert_flag'] = df['alert_flag'].replace({'yes': 1, 'no': 0, '-1': 0, '0': 0, '1': 1}).astype(int)
print(' Alert_flag binario:')
print(df['alert_flag'].value_counts())

 Alert_flag binario:
alert_flag
0    6055
1    3945
Name: count, dtype: int64

In [26]:
# CELDA 12: FECHAS → 99.5% parseadas
# 15+ formatos diferentes → datetime
def parse_date(date_str):
    if pd.isna(date_str): return pd.NaT
    date_str = str(date_str).strip()
    formats = ['%Y-%m-%d %H:%M:%S','%d-%m-%Y %H:%M','%Y-%m-%d','%d-%m-%Y']
    for fmt in formats:
        try: return pd.to_datetime(date_str, format=fmt)
        except: continue
    return pd.to_datetime(date_str, errors='coerce', dayfirst=True)

df['timestamp'] = df['timestamp'].apply(parse_date)
df['last_success_login'] = df['last_success_login'].apply(parse_date)
print(f' Timestamp: {df["timestamp"].notna().mean():.1%}')
print(df[['timestamp', 'last_success_login']].head())

/tmp/ipykernel_1818/1914035442.py:10: UserWarning: Parsing dates in %m-%d-%Y %H:%M format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(date_str, errors='coerce', dayfirst=True)
/tmp/ipykernel_1818/1914035442.py:10: UserWarning: Parsing dates in %m-%d-%Y %H:%M format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(date_str, errors='coerce', dayfirst=True)

 Timestamp: 100.0%
            timestamp  last_success_login
0 2024-08-06 16:50:00 2024-06-11 16:50:00
1 2024-06-19 22:06:00 2024-06-06 22:06:00
2 2024-08-04 22:14:00 2024-12-06 22:14:00
3 2024-06-18 07:47:00 2024-05-20 07:47:00
4 2024-04-22 10:04:00 2024-02-29 10:04:00

In [27]:
df.head(10)

,event_id,username,role,status,timestamp,ip_address,location,device,account_status,login_attempts,source_port,last_success_login,alert_flag
0,1,root,user,failed,2024-08-06 16:50:00,165.93.148.165,de,Nan,inactive,Unknown,443,2024-06-11 16:50:00,0
1,2,jdoe,guest,failed,2024-06-19 22:06:00,221.49.14.175,spain,Ubuntu,locked,Unknown,443,2024-06-06 22:06:00,1
2,3,service,user,failed,2024-08-04 22:14:00,242.73.33.181,españa,Windows,active,3.0,3389,2024-12-06 22:14:00,0
3,4,admin,guest,failed,2024-06-18 07:47:00,251.233.216.87,spain,Windows,active,4.0,unknown,2024-05-20 07:47:00,0
4,5,backup,admin,failed,2024-04-22 10:04:00,205.59.238.115,es,Windows,active,Unknown,8080,2024-02-29 10:04:00,0
5,6,service,user,failed,2024-09-05 21:44:00,231.118.88.233,usa,Nan,locked,6.0,22,NaT,1
6,7,guest,admin,success,2024-09-02 02:30:00,97.230.234.167,es,Windows,locked,2.0,443,2024-08-07 02:30:00,0
7,8,backup,guest,success,2024-02-19 15:28:00,52.89.166.75,usa,Android,inactive,3.0,3389,2023-12-29 15:28:00,1
8,9,jdoe,admin,locked,2024-04-27 01:30:00,250.126.61.226,es,Linux,active,Unknown,8080,2024-03-28 01:30:00,1
9,10,operator,guest,failed,2024-04-12 12:37:00,139.172.72.21,españa,Android,inactive,4.0,3389,2024-03-31 12:37:00,0

In [28]:
# CELDA 13: "Nan" LITERAL → Unknown
# Strings 'Nan'/'nan' → Unknown
nan_variants = ['Nan', 'nan', 'NaN', 'NULL', 'null']
df = df.replace(nan_variants, 'Unknown')
df = df.fillna('Unknown')

print(' "Nan" literales eliminados')
print(df[['device', 'location']].head(10))

 "Nan" literales eliminados
    device location
0  Unknown       de
1   Ubuntu    spain
2  Windows   españa
3  Windows    spain
4  Windows       es
5  Unknown      usa
6  Windows       es
7  Android      usa
8    Linux       es
9  Android   españa

In [29]:
# CELDA 14: IPS → unknown si inválidas
# 999.999.999.999→unknown, multicast→unknown
def clean_ip(ip):
    ip_str = str(ip).strip()
    if ip_str in ['999.999.999.999', '0.0.0.0']:
        return 'unknown'
    try:
        parts = ip_str.split('.')
        nums = [int(p) for p in parts[:4]]
        if len(parts) == 4 and all(0 <= n <= 255 for n in nums):
            return ip_str
    except:
        pass
    return 'unknown'

df['ip_address'] = df['ip_address'].apply(clean_ip)
print(' IPs validadas:')
print(df['ip_address'].value_counts().head())

 IPs validadas:
ip_address
unknown           403
165.93.148.165      1
37.108.193.190      1
4.219.162.244       1
198.13.60.89        1
Name: count, dtype: int64

In [30]:
# Confirma 0 nulos → dataset_clean_pandas.csv
print(f'Shape: {df.shape}')
print('Nulos por columna:')
nulls = df.isnull().sum()
print(nulls[nulls > 0] if nulls.sum() > 0 else ' no hay nulos')

# EXPORT
df.to_csv('dataset_clean_pandas.csv', index=False)
print('\n  dataset_clean_pandas.csv')

Shape: (10000, 13)
Nulos por columna:
 no hay nulos

  dataset_clean_pandas.csv